# Generated by Django 2.1.7 on 2019-03-06 01:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=60, verbose_name='nome')),
                ('currency', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor')),
                ('flow', models.CharField(choices=[('REC', 'Receita'), ('EXP', 'Despesa')], default='REC', max_length=3, verbose_name='tipo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
